# Generated by Django 4.0.6 on 2022-07-31 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('driver', models.CharField(max_length=500)),
                ('capacity', models.IntegerField()),
            ],
        ),
    ]
