# Generated by Django 4.0.6 on 2022-08-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='capacity',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
    ]
