# Generated by Django 4.0.6 on 2022-08-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0002_alter_bus_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
