# Generated by Django 4.0.6 on 2022-08-15 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0003_alter_bus_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='onRoute',
            field=models.BooleanField(default=False),
        ),
    ]
