# Generated by Django 4.0.6 on 2022-08-15 18:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('pax_pct', models.IntegerField(blank=True, null=True)),
                ('pax_num', models.IntegerField(blank=True, null=True)),
                ('assigned_buses', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), size=None)),
            ],
        ),
    ]
