# Generated by Django 4.0.6 on 2022-08-10 18:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='assigned_buses',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), default='', size=None),
            preserve_default=False,
        ),
    ]
