# Generated by Django 4.0.6 on 2022-08-13 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_route_assigned_buses'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='pax_num',
            field=models.CharField(default='0 Pax', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='pax_pct',
            field=models.CharField(default='0%', max_length=8),
            preserve_default=False,
        ),
    ]
