# Generated by Django 4.0.6 on 2022-08-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_route_pax_num_route_pax_pct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='pax_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='pax_pct',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
