# Generated by Django 4.0.6 on 2022-08-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('full_name', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('seat', models.IntegerField(null=True)),
                ('route', models.JSONField()),
            ],
        ),
    ]
